name: Build QuickKV

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          ninja-build \
          wget \
          build-essential \
          nlohmann-json3-dev \
          libcatch2-dev
    
    - name: Install GCC 14.2
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble main"
        sudo apt-get update
        sudo apt-get install -y gcc-14 g++-14
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
        gcc --version
        g++ --version
    
    - name: Clone and build domain-keys dependency
      run: |
        git clone https://github.com/darrylwest/cpp-domain-keys.git domain-keys-src
        cd domain-keys-src
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -GNinja
        ninja
        sudo ninja install
    
    - name: Configure CMake
      run: |
        mkdir build && cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TESTING=OFF \
          -DENABLE_TESTS=ON \
          -GNinja
    
    - name: Build
      run: |
        cd build
        ninja -j$(nproc)
    
    - name: Run tests
      run: |
        cd build
        ./unit_tests
    
    - name: Package artifacts
      run: |
        cd build
        mkdir -p artifacts/lib artifacts/include artifacts/examples
        cp libquickkv.a artifacts/lib/
        cp -r ../include/* artifacts/include/
        cp examples/* artifacts/examples/ 2>/dev/null || true
        tar -czf quickkv-ubuntu-24.04-release.tar.gz artifacts/
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: quickkv-ubuntu-24.04-release
        path: build/quickkv-ubuntu-24.04-release.tar.gz
        retention-days: 30