name: Build QuickKV

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    container: darrylwest/ubuntu24-gpp1420:latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y \
          cmake \
          ninja-build \
          wget \
          git \
          nlohmann-json3-dev
    
    - name: Verify GCC version
      run: |
        gcc --version
        g++ --version
    
    - name: Install Catch2
      run: |
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2
        git checkout v3.7.1
        cmake -B build -S . -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=/usr/local
        cmake --build build --parallel $(nproc)
        cmake --build build --target install
        cd ..
    
    - name: Clone and build domain-keys dependency
      run: |
        git clone https://github.com/darrylwest/cpp-domain-keys.git domain-keys-src
        cd domain-keys-src
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -GNinja
        ninja
        ninja install
    
    - name: Configure CMake
      run: |
        mkdir build && cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TESTING=OFF \
          -DENABLE_TESTS=ON \
          -GNinja
    
    - name: Build
      run: |
        cd build
        ninja -j$(nproc)
    
    - name: Run tests
      run: |
        ./build/unit_tests
    
    - name: Package artifacts
      run: |
        cd build
        mkdir -p artifacts/lib artifacts/include artifacts/examples
        cp libquickkv.a artifacts/lib/
        cp -r ../include/* artifacts/include/
        cp examples/* artifacts/examples/ 2>/dev/null || true
        tar -czf quickkv-ubuntu-24.04-release.tar.gz artifacts/
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: quickkv-ubuntu-24.04-release
        path: build/quickkv-ubuntu-24.04-release.tar.gz
        retention-days: 30
